/**
 * FASE 3 — DB ↔ Cloudinary cross-audit.
 * Reads every cover_url + gallery[*] from projects/artworks/furniture +
 * branding/about expectations + series.coverUrl, and checks each one against
 * the Cloudinary inventory generated by scripts/audit-cloudinary.ts.
 *
 * Fails if:
 *   - any cover_url stored in DB doesn't exist in Cloudinary
 *   - any value doesn't start with `sofi-mosquera/` (off-namespace)
 *   - any path has invalid characters (spaces, weird casing)
 *
 * Usage: pnpm --filter @sofi/db exec tsx audit-db-vs-cloudinary.ts
 */
import { config } from "dotenv";
import { resolve } from "path";
import { readFileSync, existsSync } from "fs";

config({ path: resolve(__dirname, "../../.env.local") });

const SOFI_PREFIX = "sofi-mosquera/";

interface DbValue {
  table: string;
  slug: string;
  field: string;
  value: string;
  isPublicId: boolean;
}

interface InventoryFile {
  cloud: string;
  classified: { sofi: string[]; otherProject: string[]; rootStray: unknown[]; ambiguous: unknown[] };
}

const VIDEO_PREFIX = "video:";

function isCloudinaryUrl(v: string): boolean {
  return /^https?:\/\/res\.cloudinary\.com\//.test(v);
}

/** Strip "video:" prefix used in DB to mark video-poster public_ids. */
function stripVideoPrefix(v: string): string {
  return v.startsWith(VIDEO_PREFIX) ? v.slice(VIDEO_PREFIX.length) : v;
}

function extractPublicIdFromUrl(url: string): string | null {
  // Format: https://res.cloudinary.com/{cloud}/image/upload/[transforms/][vN/]{public_id}[.ext]
  const m = url.match(
    /^https?:\/\/res\.cloudinary\.com\/[^/]+\/(?:image|video)\/upload\/(.+)$/
  );
  if (!m) return null;
  let path = m[1];
  // Drop transformation segment(s): segments containing comma or starting with known prefixes
  // and version segment (v + digits)
  const segs = path.split("/");
  const cleaned: string[] = [];
  let inHead = true;
  for (const s of segs) {
    if (inHead) {
      // transformation segment if it contains comma or matches known param prefixes
      if (/[,]/.test(s) || /^[a-z]_/i.test(s)) continue;
      // version segment
      if (/^v\d+$/i.test(s)) continue;
      inHead = false;
    }
    cleaned.push(s);
  }
  let pid = cleaned.join("/");
  // strip extension
  pid = pid.replace(/\.(jpe?g|png|webp|avif|gif|mp4|mov|webm)$/i, "");
  return pid || null;
}

async function main() {
  const url = process.env.DATABASE_URL_UNPOOLED;
  if (!url) {
    console.error("DATABASE_URL_UNPOOLED missing");
    process.exit(1);
  }
  const inventoryPath = resolve(__dirname, "../../tmp-cloudinary-inventory.json");
  const STALE_MS = 24 * 60 * 60 * 1000; // 24h
  let needsRefresh = !existsSync(inventoryPath);
  if (!needsRefresh) {
    const fs = await import("fs");
    const ageMs = Date.now() - fs.statSync(inventoryPath).mtimeMs;
    if (ageMs > STALE_MS) needsRefresh = true;
  }
  if (needsRefresh) {
    console.log("Inventory missing or stale — regenerating via scripts/audit-cloudinary.ts");
    const { spawnSync } = await import("child_process");
    const res = spawnSync(
      "npx",
      ["tsx", resolve(__dirname, "../../scripts/audit-cloudinary.ts")],
      { stdio: "inherit", shell: true }
    );
    if (res.status !== 0) {
      console.error("Inventory generation failed.");
      process.exit(1);
    }
  }
  const inv = JSON.parse(readFileSync(inventoryPath, "utf-8")) as InventoryFile;
  const cloudinarySet = new Set(inv.classified.sofi);

  const { neon } = await import("@neondatabase/serverless");
  const sql = neon(url);

  console.log("\n=== FASE 3 — DB ↔ Cloudinary cross-audit ===\n");

  const findings: DbValue[] = [];

  // projects
  const projects = (await sql`
    SELECT slug, cover_url, gallery FROM projects WHERE visible = true ORDER BY position
  `) as Array<{ slug: string; cover_url: string | null; gallery: string[] | null }>;

  for (const p of projects) {
    if (p.cover_url)
      findings.push({
        table: "projects",
        slug: p.slug,
        field: "cover_url",
        value: p.cover_url,
        isPublicId: !isCloudinaryUrl(p.cover_url),
      });
    for (const g of p.gallery ?? []) {
      findings.push({
        table: "projects",
        slug: p.slug,
        field: "gallery[]",
        value: g,
        isPublicId: !isCloudinaryUrl(g),
      });
    }
  }

  // artworks
  const artworks = (await sql`
    SELECT slug, cover_url, context_url, gallery FROM artworks ORDER BY position
  `) as Array<{ slug: string; cover_url: string | null; context_url: string | null; gallery: string[] | null }>;

  for (const a of artworks) {
    if (a.cover_url)
      findings.push({
        table: "artworks",
        slug: a.slug,
        field: "cover_url",
        value: a.cover_url,
        isPublicId: !isCloudinaryUrl(a.cover_url),
      });
    if (a.context_url)
      findings.push({
        table: "artworks",
        slug: a.slug,
        field: "context_url",
        value: a.context_url,
        isPublicId: !isCloudinaryUrl(a.context_url),
      });
    for (const g of a.gallery ?? []) {
      findings.push({
        table: "artworks",
        slug: a.slug,
        field: "gallery[]",
        value: g,
        isPublicId: !isCloudinaryUrl(g),
      });
    }
  }

  // furniture
  const furniture = (await sql`
    SELECT slug, cover_url, gallery FROM furniture ORDER BY position
  `) as Array<{ slug: string; cover_url: string | null; gallery: string[] | null }>;

  for (const f of furniture) {
    if (f.cover_url)
      findings.push({
        table: "furniture",
        slug: f.slug,
        field: "cover_url",
        value: f.cover_url,
        isPublicId: !isCloudinaryUrl(f.cover_url),
      });
    for (const g of f.gallery ?? []) {
      findings.push({
        table: "furniture",
        slug: f.slug,
        field: "gallery[]",
        value: g,
        isPublicId: !isCloudinaryUrl(g),
      });
    }
  }

  // series
  const series = (await sql`
    SELECT slug, cover_url FROM series ORDER BY position
  `) as Array<{ slug: string; cover_url: string | null }>;

  for (const s of series) {
    if (s.cover_url)
      findings.push({
        table: "series",
        slug: s.slug,
        field: "cover_url",
        value: s.cover_url,
        isPublicId: !isCloudinaryUrl(s.cover_url),
      });
  }

  console.log(`Total values to verify: ${findings.length}\n`);

  let fail = 0;
  let warn = 0;
  let ok = 0;
  const offNamespace: DbValue[] = [];
  const missingInCloudinary: DbValue[] = [];
  const fullUrlValues: DbValue[] = [];
  const validIssues: DbValue[] = [];

  for (const f of findings) {
    if (!f.isPublicId) {
      fullUrlValues.push(f);
      // try to extract public_id and check
      const pid = extractPublicIdFromUrl(f.value);
      if (pid) {
        if (!pid.startsWith(SOFI_PREFIX)) {
          offNamespace.push({ ...f, value: pid });
          fail++;
        } else if (!cloudinarySet.has(pid)) {
          missingInCloudinary.push({ ...f, value: pid });
          fail++;
        } else {
          ok++;
        }
      } else {
        validIssues.push(f);
        warn++;
      }
      continue;
    }
    // public_id (may carry the "video:" prefix used to mark video-poster sources)
    const bare = stripVideoPrefix(f.value);
    if (/[\s]|[A-Z]/.test(bare) || bare.includes("..")) {
      validIssues.push(f);
      warn++;
    }
    if (!bare.startsWith(SOFI_PREFIX)) {
      offNamespace.push(f);
      fail++;
      continue;
    }
    if (!cloudinarySet.has(bare)) {
      missingInCloudinary.push(f);
      fail++;
      continue;
    }
    ok++;
  }

  console.log(`✓ ok in cloudinary:      ${ok}`);
  console.log(`✗ missing in cloudinary: ${missingInCloudinary.length}`);
  console.log(`✗ off namespace:         ${offNamespace.length}`);
  console.log(`⚠ full URLs in db:        ${fullUrlValues.length} (should be public_ids)`);
  console.log(`⚠ format issues:         ${validIssues.length}`);

  if (missingInCloudinary.length > 0) {
    console.log("\n--- Missing in Cloudinary (DB has these public_ids but they're not uploaded) ---");
    for (const m of missingInCloudinary.slice(0, 30)) {
      console.log(`  [${m.table}] ${m.slug}.${m.field} → ${m.value}`);
    }
    if (missingInCloudinary.length > 30) console.log(`  ... and ${missingInCloudinary.length - 30} more`);
  }

  if (offNamespace.length > 0) {
    console.log("\n--- Off-namespace (not under sofi-mosquera/) ---");
    for (const m of offNamespace.slice(0, 30)) {
      console.log(`  [${m.table}] ${m.slug}.${m.field} → ${m.value}`);
    }
    if (offNamespace.length > 30) console.log(`  ... and ${offNamespace.length - 30} more`);
  }

  if (fullUrlValues.length > 0) {
    console.log("\n--- Full URLs stored in DB (cosmetic — should be public_ids per AGENTS.md) ---");
    for (const m of fullUrlValues.slice(0, 5)) {
      console.log(`  [${m.table}] ${m.slug}.${m.field} → ${m.value.substring(0, 100)}...`);
    }
    if (fullUrlValues.length > 5) console.log(`  ... and ${fullUrlValues.length - 5} more`);
  }

  if (validIssues.length > 0) {
    console.log("\n--- Format issues (spaces, uppercase, etc.) ---");
    for (const m of validIssues) {
      console.log(`  [${m.table}] ${m.slug}.${m.field} → ${m.value}`);
    }
  }

  console.log(`\n=== ${fail === 0 ? "DB↔Cloudinary IN SYNC" : `${fail} broken reference(s)`} ===\n`);
  process.exitCode = fail === 0 ? 0 : 1;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
